# Generated by Django 4.0.5 on 2022-06-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_document',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
