# Generated by Django 4.0.5 on 2022-06-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant_cv',
            old_name='id',
            new_name='applicant_id',
        ),
        migrations.RenameField(
            model_name='applicant_document',
            old_name='id',
            new_name='applicant_document_id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='id',
            new_name='application_id',
        ),
        migrations.RenameField(
            model_name='candidate_evaluation',
            old_name='id',
            new_name='candidate_evaluation_id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='id',
            new_name='companey_id',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='id',
            new_name='education_id',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='id',
            new_name='experiance_id',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='id',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='job_category',
            old_name='id',
            new_name='job_category_id',
        ),
        migrations.RenameField(
            model_name='job_description_document',
            old_name='id',
            new_name='job_description_id',
        ),
        migrations.RenameField(
            model_name='job_platforms',
            old_name='id',
            new_name='job_platform_id',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='id',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='skill_set',
            old_name='id',
            new_name='skill_set_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_role',
            old_name='id',
            new_name='user_role_id',
        ),
    ]
